---
title: "Analysis1"
author: "Michael Xiao"
date: "12/29/2021"
output: pdf_document
---
# Initial Analysis of Data Using Absence-Presence Model

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir="/home/michael_xiao/T/st")
```

```{r}
# load packages and data
require("sf")
require(tidyverse)
require(ggbiplot)
require(plotly)
require(mgcv)
require(GGally)
require(car)
require(gstat)
require(iml)

data = read_sf("Final_Data/data.shp")
data$wf = as.integer(data$wf_count>0)
data$pb = as.integer(data$pb_count>0)
```

```{r}
# utilities
covariates = colnames(data)[c(24:41,75:77,88:91)]

# makes formula using x and y
make_form = function(x=c("pb", covariates), y="wf", no_smooth=c("pb")) {
  for (i in 1:length(x)) {
    if (x[i] %in% no_smooth) {
      next
    } else {
      x[i] = paste("s(", x[i], ")", sep="")
    }
  }
  raw_form = paste(x, collapse=" + ")
  return (formula(paste(y, " ~ ", raw_form)))
}

# removes feature from vector
rem_item = function(vec, item) {
  index = which(vec %in% item)
  return (vec[-index])
}

# plot map with a single variable
plot_map = function(data, var, type="c", direction=1) {
  if (type == "c") {
    ggplot(data=data) +
      geom_sf(aes(fill=!!sym(var), color=!!sym(var))) +
      scale_fill_viridis_c(direction=direction) +
      scale_color_viridis_c(direction=direction)
  } else if (type == "d") {
    ggplot(data=data) +
      geom_sf(aes(fill=as.factor(!!sym(var)), color=as.factor(!!sym(var)))) +
      scale_fill_viridis_d(direction=direction) +
      scale_color_viridis_d(direction=direction)
  }
}
```

```

{r}
plot_map(data, "wf", "d")
plot_map(data, "pb", "d")
```



## Colinearity Check

```{r}
# first look at pairwise correlations
data_cov = st_drop_geometry(data[,covariates])
png("Plots/corr_heat.png",width=5*length(covariates), height=3*length(covariates), units="cm", res=100)
ggcorr(data_cov, label=T, legend.size=30)
dev.off()

# drop pPrivate, perc_cloud
cov_dropped = rem_item(covariates, c("pPrivate", "perc_cloud"))
data_dropped = st_drop_geometry(data[,cov_dropped])

# compute vif of new set of covariates
lin_form = make_form(x=cov_dropped, no_smooth=cov_dropped)
model = lm(lin_form, data=data)
vif(model)

# drop vpmax, elevation
cov_dropped2 = rem_item(cov_dropped, c("vpmax", "elevation"))
lin_form2 = make_form(x=cov_dropped2, no_smooth=cov_dropped2)
model2 = lm(lin_form2, data=data)
vif(model2)

# save new covariates
cov_cleaned = cov_dropped2
```

## Initial Fitting and Diagnosis of a Naive GAM Model

```{r}
naive_form = make_form(c("pb", cov_cleaned))
gam_naive = gam(naive_form, data=data, family=binomial)

summary(gam_naive)
```


```{r}
plot(gam_naive, scale=0, rug=T)
```

```{r}
# spatial correlation analysis
res = gam_naive$residuals
data$res = res
x = data$CENTROID_X
y = data$CENTROID_Y
vario = as.data.frame(cbind(res=res, x=x, y=y))
v = variogram(res~1, data=data)

v_dir = variogram(res~1, data=data, alpha=c(0,45,90,130))
plot(v)
plot(v_dir)
plot_map(data %>% filter(res>0), "res", direction=-1)
```



```{r}
colnames(data)
ggplot(data=data, aes(x=tree, y=shrub)) +
  geom_point(alpha=0.3)

```

## Re-Do analysis on grid cells where percent tree is greater than 50

```{r}
plot_map(data=data, var="tree")
```

```{r}
# get these data
data_tree = data %>% filter(tree > 0.5)

# re-do collinearity check
# first look at pairwise correlations
tree_cov = st_drop_geometry(data_tree[,covariates])
png("Plots/corr_heat_tree.png",width=5*length(covariates), height=3*length(covariates), units="cm", res=100)
ggcorr(tree_cov, label=T, legend.size=30)
dev.off()

# drop elevation
tree_dropped = rem_item(covariates, c("elevation"))
data_tree_dropped = st_drop_geometry(data_tree[,cov_dropped])

# compute vif of new set of covariates
lin_form_tree = make_form(x=tree_dropped, no_smooth=tree_dropped)
model_tree = lm(lin_form_tree, data=data_tree)
vif(model_tree)

# drop pPrivate
tree_dropped2 = rem_item(tree_dropped, c("pPrivate"))
lin_form_tree2 = make_form(x=tree_dropped2, no_smooth=tree_dropped2)
model_tree2 = lm(lin_form_tree2, data=data_tree)
vif(model_tree2)

# save new covariates
cov_cleaned_tree = tree_dropped2
```

```{r}
ggplot(data=data_tree) +
  geom_sf(color="blue")
```


```{r}
# fit tree gam model
tree_form = make_form(c("pb", cov_cleaned_tree))
gam_tree = gam(tree_form, data=data_tree, family=binomial)

summary(gam_tree)
```

```{r}
plot(gam_tree, scale=0)
```

```{r}
# spatial correlation analysis
res = gam_tree$residuals
data_tree$res = res
x = data_tree$CENTROID_X
y = data_tree$CENTROID_Y
vario = as.data.frame(cbind(res=res, x=x, y=y))
v = variogram(res~1, data=data_tree)

v_dir = variogram(res~1, data=data_tree, alpha=c(0,45,90,130))
plot(v)
plot(v_dir)
plot_map(data_tree %>% filter(res>0), "res", direction=-1)
```


```{r}
bubble(data_tree, "res", col = c("black","grey"), main = "Residuals", xlab = "X-coordinates", ylab = "Y-coordinates")
```

## Try taking out not Federal, State, Private (no good)

```{r}
cov_lo = rem_item(covariates, c("elevation", "pCounty", "pCity", "pNP", "pSD"))
lin_form_lo = make_form(x=c("pb",cov_lo), no_smooth=c("pb",cov_lo))
model_tree = lm(lin_form_lo, data=data_tree)
vif(model_tree) # no good
```
## Try taking out temp

```{r}
# remove temp, pPrivate, coordiantes
cov_no_temp = rem_item(covariates, c("temp", "pPrivate", "CENTROID_Y"))
lin_form_nt = make_form(x=c("pb", cov_no_temp), no_smooth=c("pb", cov_no_temp))
model_nt = lm(lin_form_nt, data=data)
vif(model_nt)

# nt_cov = st_drop_geometry(data[,cov_no_temp])
# png("Plots/corr_heat_nt.png",width=5*length(cov_no_temp), height=3*length(cov_no_temp), units="cm", res=100)
# ggcorr(nt_cov, label=T, legend.size=30)
# dev.off()
```

```{r}
# fit gam
nt_form = make_form(c("pb", cov_no_temp))
gam_nt = gam(nt_form, data=data, family=binomial)

summary(gam_nt)
```

```{r}
plot(gam_nt, scale=0, rug=T)
```

```{r}
# spatial correlation
res = gam_nt$residuals
data$res = res
x = data$CENTROID_X
y = data$CENTROID_Y
vario = as.data.frame(cbind(res=res, x=x, y=y))
v = variogram(res~1, data=data)

v_dir = variogram(res~1, data=data, alpha=c(0,45,90,130))
plot(v)
plot(v_dir)
plot_map(data %>% filter(res>0), "res", direction=-1)
```

## Replace individual coordiantes with interaction of the two

```{r}
cov_tree1 = c(rem_item(cov_cleaned_tree, c("CENTROID_X", "CENTROID_Y")), "CENTROID_X, CENTROID_Y")
tree_form2 = make_form(x=c("pb", cov_tree1), y="wf")

gam_co_int = gam(tree_form2, data=data_tree, family=binomial)

summary(gam_co_int)
```

```{r}
plot(gam_co_int, scale=0)
```


```{r}
# now try the same thing for overall
cov1 = c(rem_item(cov_cleaned, c("CENTROID_X", "CENTROID_Y")), "CENTROID_X, CENTROID_Y")
form2 = make_form(x=c("pb", cov1), y="wf")

gam_int = gam(form2, data=data, family=binomial)

summary(gam_int)
```

```{r}
plot(gam_int, scale=0)
```

```{r}
vis.gam(gam_int)
```

```{r}
# fit a gam for each individual variable
covariates
```

```{r}
model = gam(wf~s(ppt)+0, data=data, family=binomial)
summary(model)$s.table

sig_table = list()
for (c in covariates) {
  f = formula(paste("wf~s(", c, ")+0", sep=""))
  model = gam(f, data=data, family=binomial)
  #plot(model)
  sig = summary(model)$s.table
  sig_table[[c]] = sig
}
do.call(rbind, sig_table)
```

```{r}
sig_table
```





